---
title: "Week 2"
author: "Jan Matthias"
date: "2023-03-03"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(epiwraps)
})
```

```{r annotationhub}
# importing the indexes for the various species 
ah <- AnnotationHub()
# to query the AH programmatically:
mus_musculus <- query(ah, c("Mus Musculus", "ensembl", "GRCm38", "version 102"))
mus_genome <- query(ah, c("dna_sm", "ensembl"))
drosophila_mel <- query(ah, c("dna_sm", "ensembl"))

# other way of checking for the correct AH number 
display(ah)

# mouse genome 
mus_musculus_nnsb <- ah[["AH89211"]]
mus_musculus_nnsb

# mouse genome two bit format 
mus_genome_nnsb <- ah[["AH88477"]]
mus_genome_nnsb

# drosophila melanogaster
drosophila_nnsb <- ah[["AH95713"]]
drosophila_nnsb 

# query(ah, c("Drosophila", "ensembl"))
# transcript, subset that gets targeted 
```

```{r pressure}
#?genes --> to search how to, plus need to filter 
gns <- genes(mus_musculus_nnsb, filter=GeneBiotypeFilter("protein_coding"))
length(unique(gns$gene_id))
```
```{r part 3}
exsPerTx <- exonsBy(mus_musculus_nnsb, column=c("tx_id","tx_biotype"), 
                    filter=TxBiotypeFilter("protein_coding"))
# extracted the exons of protein-coding transcripts, and split them by transcript 
exons_mouse <- width(exsPerTx)
exons_mouse
# add the by width 
hist(sum(exons_mouse), breaks = 250)

# plotting of the protein coding transcripts 
```